//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.30 at 11:28:32 PM UTC 
//


package net.java.dev.wadl._2009._02;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.java.dev.wadl._2009._02 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.java.dev.wadl._2009._02
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WadlApplication }
     * 
     */
    public WadlApplication createApplication() {
        return new WadlApplication();
    }

    /**
     * Create an instance of {@link WadlDoc }
     * 
     */
    public WadlDoc createDoc() {
        return new WadlDoc();
    }

    /**
     * Create an instance of {@link Grammars }
     * 
     */
    public Grammars createGrammars() {
        return new Grammars();
    }

    /**
     * Create an instance of {@link Include }
     * 
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link WadlResources }
     * 
     */
    public WadlResources createResources() {
        return new WadlResources();
    }

    /**
     * Create an instance of {@link WadlResource }
     * 
     */
    public WadlResource createResource() {
        return new WadlResource();
    }

    /**
     * Create an instance of {@link WadlParam }
     * 
     */
    public WadlParam createParam() {
        return new WadlParam();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link WadlMethod }
     * 
     */
    public WadlMethod createMethod() {
        return new WadlMethod();
    }

    /**
     * Create an instance of {@link WadlRequest }
     * 
     */
    public WadlRequest createRequest() {
        return new WadlRequest();
    }

    /**
     * Create an instance of {@link WadlRepresentation }
     * 
     */
    public WadlRepresentation createRepresentation() {
        return new WadlRepresentation();
    }

    /**
     * Create an instance of {@link WadlResponse }
     * 
     */
    public WadlResponse createResponse() {
        return new WadlResponse();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

}
